=begin
#gBizINFO REST API

#<div>各REST APIはHTTPリクエストヘッダX-hojinInfo-api-tokenに動作確認用のAPIトークンDTcLxzo1lZaUYaQPVdSRxdS4MzlXNCs4を指定して動作を確認することができます。</div><div>※動作確認用のAPIトークンはこのページでの動作確認でのみ使用してください。</div><div>※REST APIを利用する際は必ず、<a href='https://info.gbiz.go.jp/hojin/api_registration/form'>Web API利用申請</a>を行い、APIトークンを取得してください。</div>

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Gbizinfo
  class WomenActivityInfos < ApiModelBase
    # 女性管理職人数
    attr_accessor :female_share_of_manager

    # 女性役員人数
    attr_accessor :female_share_of_officers

    # 労働者に占める女性労働者の割合
    attr_accessor :female_workers_proportion

    # 労働者に占める女性労働者の割合種別
    attr_accessor :female_workers_proportion_type

    # 管理職に占める女性の割合
    attr_accessor :gender_total_of_manager

    # 役員全体人数（男女計）
    attr_accessor :gender_total_of_officers

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'female_share_of_manager' => :'female_share_of_manager',
        :'female_share_of_officers' => :'female_share_of_officers',
        :'female_workers_proportion' => :'female_workers_proportion',
        :'female_workers_proportion_type' => :'female_workers_proportion_type',
        :'gender_total_of_manager' => :'gender_total_of_manager',
        :'gender_total_of_officers' => :'gender_total_of_officers'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'female_share_of_manager' => :'Integer',
        :'female_share_of_officers' => :'Integer',
        :'female_workers_proportion' => :'Float',
        :'female_workers_proportion_type' => :'String',
        :'gender_total_of_manager' => :'Integer',
        :'gender_total_of_officers' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Gbizinfo::WomenActivityInfos` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Gbizinfo::WomenActivityInfos`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'female_share_of_manager')
        self.female_share_of_manager = attributes[:'female_share_of_manager']
      end

      if attributes.key?(:'female_share_of_officers')
        self.female_share_of_officers = attributes[:'female_share_of_officers']
      end

      if attributes.key?(:'female_workers_proportion')
        self.female_workers_proportion = attributes[:'female_workers_proportion']
      end

      if attributes.key?(:'female_workers_proportion_type')
        self.female_workers_proportion_type = attributes[:'female_workers_proportion_type']
      end

      if attributes.key?(:'gender_total_of_manager')
        self.gender_total_of_manager = attributes[:'gender_total_of_manager']
      end

      if attributes.key?(:'gender_total_of_officers')
        self.gender_total_of_officers = attributes[:'gender_total_of_officers']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          female_share_of_manager == o.female_share_of_manager &&
          female_share_of_officers == o.female_share_of_officers &&
          female_workers_proportion == o.female_workers_proportion &&
          female_workers_proportion_type == o.female_workers_proportion_type &&
          gender_total_of_manager == o.gender_total_of_manager &&
          gender_total_of_officers == o.gender_total_of_officers
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [female_share_of_manager, female_share_of_officers, female_workers_proportion, female_workers_proportion_type, gender_total_of_manager, gender_total_of_officers].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
